FROM mambaorg/micromamba:1.5-bullseye-slim

ARG ENV_FILE=environment.yml

COPY ${ENV_FILE} /tmp/environment.yml

ARG MAMBA_DOCKERFILE_ACTIVATE=1

ENV PATH="$MAMBA_ROOT_PREFIX/bin:$PATH"

RUN micromamba install \
        -c defaults \
        -c bioconda \
        -c conda-forge \
        -y \
        -n base \
        git \
        gcc_linux-64 \
        gxx_linux-64 \
    && micromamba install \
        -y \
        -n base \
        -f /tmp/environment.yml \
    && micromamba clean --all --yes

USER root

RUN BIGSCAPE_DIR=$(python -c "import big_scape, os; print(os.path.dirname(big_scape.__file__))") \
    && mkdir -p "${BIGSCAPE_DIR}/MIBiG" \
    && chmod -R a+rwX "${BIGSCAPE_DIR}/MIBiG"

USER mambauser

WORKDIR /home/mambauser/app

CMD ["/bin/bash"]