FROM mambaorg/micromamba:1.5-bullseye-slim

USER root

RUN apt-get update && apt-get install -y \
    wget \
    gzip \
    git \
    && rm -rf /var/lib/apt/lists/*

ENV MAMBA_DOCKERFILE_ACTIVATE=1

COPY environment.yml /tmp/environment.yml

RUN micromamba create -y \
    -n poem_env \
    python=3.7 \
    keras=2.2.4 \
    tensorflow=1.14 \
    theano=1.0.4 \
    numpy=1.16 \
    perl-xml-simple \
    perl \
    blast=2.9 \
    biopython \
    networkx \
    diamond \
    prokka=1.12 \
    idba \
    cd-hit \
    art \
    -c conda-forge \
    -c bioconda

RUN micromamba install -y \
    -n poem_env \
    -c bioconda \
    diamond \
    && micromamba clean --all --yes

ENV PATH="/opt/conda/envs/poem_env/bin:$PATH"

WORKDIR /opt

RUN git clone https://github.com/Rinoahu/POEM_py3k.git POEM


WORKDIR /opt/POEM

RUN mkdir -p database/cog/cog2014

RUN wget -q -c \
ftp://ftp.ncbi.nih.gov/pub/COG/COG2014/data/*2014* \
-P database/cog/cog2014/

RUN gunzip database/cog/cog2014/prot2003-2014.fa.gz

RUN micromamba run -n poem_env diamond makedb \
    --in database/cog/cog2014/prot2003-2014.fa \
    -d database/cog/cog2014/cog2014

ENV PATH="/opt/conda/envs/poem_env/bin:$PATH"


WORKDIR /opt/POEM